---
- fail:
    msg: "You should specify the 'datacenter' property!"
  when: datacenter is undefined
- fail:
    msg: "You should specify the 'networkID' property!"
  when: networkID is undefined
- fail:
    msg: "You should specify the 'groupID' property!"
  when: groupID is undefined
- fail:
    msg: "You should specify the 'apiV1Key' property!"
  when: apiV1Key is undefined
- fail:
    msg: "You should specify the 'apiV1Passwd' property!"
  when: apiV1Passwd is undefined
- fail:
    msg: "You should specify the 'apiV2User' property!"
  when: apiV2User is undefined
- fail:
    msg: "You should specify the 'apiV2Passwd' property!"
  when: apiV2Passwd is undefined
- fail:
    msg: "You should specify the 'rootPasswd' property!"
  when: rootPasswd is undefined
- fail:
    msg: "You should specify the 'controllerIP' property!"
  when: controllerIP is undefined
- fail:
    msg: "You should specify the 'platformID' property!"
  when: platformID is undefined
- fail:
    msg: "You should specify the 'rootPasswd' property!"
  when: rootPasswd is undefined
- fail:
    msg: "Root password is not valid.It should have at least: 2 uppercase letters, 1 special case letter, 2 digits, 2 lowercase letters and not include \",',° or &. Length 8."
  when: not (rootPasswd | match("^(?=.*[A-Z].*[A-Z])(?=.*[!@#+%?<>/\\\\-_$&*.])(?!.*[&'\"°])(?=.*[0-9].*[0-9])(?=.*[a-z].*[a-z]).{8,}$"))