---
name: C3DNA Platform Component For AEM Customers
shortDescription: Application lifecycle management
public: false
author: C3DNA
organization: C3DNA
defaultPlaybook: playbook.yml
imagePath: https://raw.github.com/clc-runner/Assets/master/c3dna.png
description: C3DNA Platform

fields:
- displayName: Datacenter
  name: datacenter
  required: true
  type: datacenters
- displayName: Network
  name: networkID
  parent: datacenter
  required: true
  type: networks
- displayName: Group
  name: groupID
  parent: datacenter
  required: true
  type: groups
- displayName: Server Name
  name: serverName
  required: true
  default: C3DP
  type: text
- displayName: V1 API Key
  name: apiV1Key
  required: true
  type: text
- displayName: V1 API Password
  name: apiV1Passwd
  required: true
  type: text
- displayName: Root Password For servers
  name: rootPasswd
  type: password
  required: true
- displayName: Controller IP Address
  name: controllerIP
  type: text
  required: true
- displayName: Platform ID
  name: platformID
  type: text
  required: true
- displayName: Cluster Key
  name: clusterID
  type: text
  required: true
  default: CTL_Cloud
