---
- name: check specified properties
  hosts: localhost
  roles:
  - role: checkproperties
- name: check credentials v1
  hosts: localhost
  roles:
  - role: checkV1
- name: infrastructure
  hosts: localhost
  vars:
    srv_template: BOSH-OPENSTACK-CLC-UBUNTU-TRUSTY-GO_AGENT_3062
    srv_disks:
    - { sizeGB: 200, type: raw }
    srv_mem: "{{ mem | d(8) }}"
    srv_cpu: "{{ cpu | d(2) }}"
    srv_name: "{{ serverName | d('C3DP') }}"
    srv_pass: "{{ rootPasswd }}"
  roles:
  - role: server

- name: dependencies
  hosts: servers
  gather_facts: false
  tasks:
  # python not in bosh stemcell == not ansible-able
  - name: ensure python
    raw: which python || (apt-get update && apt-get install -qy python python-dev python-pip libxml2-dev libxslt1-dev)

- name: write image
  hosts: servers
  vars:
    url: http://bpimager.canada.os.ctl.io/c3dna/AEM-PLAT-disk1.raw.gz
    device: /dev/sdb
  roles:
  - bpimager
  tasks:
  - debug: var=ansible_default_ipv4

- name: popdisk
  hosts: localhost
  roles:
  - { role: popdisk , ansible_hostname: "{{ groups.servers[0] }}", wait_popdisk: true }

- name: add public IP
  hosts: servers
  roles:
  - {role: addpublicip, ansible_hostname: "{{ groups.servers[0] }}", wait_addpublicip: true }

- name: get public IP
  hosts: servers
  roles:
- role: getpublicip

- name: Resize Disk Step 1
  hosts: servers
  vars:
    step: 1
  roles:
  - role: resizedisk

- name: wait
  hosts: localhost
  tasks:
    - wait_for:
        host: "{{ item.details.ipAddresses[0]['internal'] }}"
        port: 22
        delay: 5
        timeout: 320
      with_items: '{{ serverInfos.servers }}'

- name: Resize Disk Step 2
  hosts: servers
  vars:
    step: 2
  roles:
  - role: resizedisk

- name: load configuration
  hosts: servers
  roles:
  - c3dna
