- name: download apiv1
  get_url:
    url: https://github.com/ack/clc-bin/releases/download/v1/apiv1.linux
    dest: /tmp/apiv1
    mode: 0755
- name: post body
  copy: content="{{ body | to_json }}" dest="/tmp/payload.json"
- debug:
    msg: "Sending login request with the following body: {{ body | to_json }}"
- block:
      - name: check credential
        raw: /tmp/apiv1 -endpoint https://api.ctl.io/REST/Auth/Logon/
           -method POST -key '{{apiV1Key}}' -pass '{{apiV1Passwd}}' < /tmp/payload.json
        register: apicall
  rescue:
    - fail: msg="Credentials for API v1 are not correct. Please provide correct credentials and execute the job again"
